# SPDX-FileCopyrightText: Copyright 2026 zjab
# SPDX-License-Identifier: LGPL-2.1-or-later

[versions]
agp = "8.13.1"
kotlin = "2.0.21"

[libraries]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
